name: Build

on:
  - push

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables
        id: variables
        run: |
          DOCKER_IMAGE_VERSION=${GITHUB_REF_NAME}-$(date +%Y%m%d%H%M%S)
          echo "::set-output name=version::$DOCKER_IMAGE_VERSION"
          echo "::set-output name=branch::$GITHUB_REF_NAME"

      - name: Update spec
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'spec.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.variables.outputs.version }}
          branch: ${{ steps.variables.outputs.branch }}
          createPR: false
          message: 'chore: Bump Docker Image tag [skip ci]'

  release:
    name: Release application
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        run: git pull

      - name: Create Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits

      - name: Deploy Release
        if: ${{ steps.semantic_release.outputs.new_release_published == 'true' }}
        uses: ./.github/workflows/deploy.yaml@v1.21.0
