name: Deploy

on:
  workflow_dispatch:

jobs:
  integration-aws:
    runs-on: ubuntu-latest
    environment: "integration:aws"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  integration-azure:
    runs-on: ubuntu-latest
    environment: "integration:azure"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  staging-aws:
    runs-on: ubuntu-latest
    environment: "staging:aws"
    needs:
      - integration-aws
      - integration-azure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  staging-azure:
    runs-on: ubuntu-latest
    environment: "staging:azure"
    needs:
      - integration-aws
      - integration-azure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  production-aws-1:
    runs-on: ubuntu-latest
    environment: "production:aws:1"
    needs:
      - staging-aws
      - staging-azure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  production-aws-2:
    runs-on: ubuntu-latest
    environment: "production:aws:2"
    needs:
      - production-aws-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  production-azure-1:
    runs-on: ubuntu-latest
    environment: "production:azure:1"
    needs:
      - staging-aws
      - staging-azure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  production-azure-2:
    runs-on: ubuntu-latest
    environment: "production:azure:2"
    needs:
      - production-azure-1
    steps:
      - name: Checkout
        uses: actions/checkout@v2